# Generated by Django 2.0.2 on 2019-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': 'Galería', 'verbose_name_plural': 'Pasteles'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tittle',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
