# Generated by Django 2.2.1 on 2019-05-31 02:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=40)),
                ('last_names', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Ingredient')),
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('units', models.CharField(choices=[('g', 'gramos(s)'), ('kg', 'kilogramo(s)'), ('pz', 'pieza(s)')], default='g', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Client')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('feeds', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Shape'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='ingredients',
            field=models.ManyToManyField(to='orders.Ingredient'),
        ),
        migrations.AddField(
            model_name='cake',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor'),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Shape'),
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together={('shape', 'ingredient')},
        migrations.AddField(
            model_name='flavor',
            name='ingredients',
            field=models.ManyToManyField(to='orders.Ingredient'),
        ),
        migrations.CreateModel(
            name='RecommendedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Shape')),
            ],
            options={
                'unique_together': {('shape', 'flavor')},
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Ingredient')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Shape')),
            ],
            options={
                'unique_together': {('shape', 'ingredient')},
            },
        ),
    ]
